<?php

namespace AcReims\StatsBundle\Repository;

/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends \Doctrine\ORM\EntityRepository
{
	// NOTE : Avec doctrine, il est impossible de réaliser ceci directement :
	// 	'INSERT INTO stats (annee, mois, jour, heure, type) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE cpt=cpt+1' en doctrine
	// 	$v1 = date("Y"); $v2 = date("m"); $v3 = date("j"); $v4 = date("H"); $v5="user";
	// On doit donc passer en 2 phases dans un service, une de lecture et si inexistant, on crée, sinon, on incrémente


	/**
	 * Charger la statistique horaire correspondant à ce profil
	 *
	 * @param $profil Profil utilisateur
	 */
	public function lireStat($profil)
	{
		// Création requête
		$qb = $this->createQueryBuilder('s');
		// Clauses Where
		$qb->where('s.annee = :annee')->setParameter('annee', date("Y"))	 		
		   ->andWhere('s.mois = :mois')->setParameter('mois', date("m")) 		
		   ->andWhere('s.jour = :jour')->setParameter('jour', date("j")) 		
		   ->andWhere('s.heure = :heure')->setParameter('heure', date("H")) 		
		   ->andWhere('s.profil = :profil')->setParameter('profil', $profil) 		
		;
		// Retourne le resultat
		return $qb->getQuery()->getResult();
	}

}
