services:

    # Service de gestion de l'entité de statistiques
    ac_reims_stats.entity:
        class: AcReims\StatsBundle\Service\Stats
        public: true
        arguments: ['@doctrine.orm.entity_manager']


