services:

    ### Service de gestion de l'entité de statistiques
    # Definition principale
    AcReims\StatsBundle\Service\Stats:
        public: true
        arguments: ['@doctrine.orm.entity_manager', '@session']
    # Son alias nécessaire pour l'injection de dépendances (sinon dépréciation à partir de symfony 3.3 et non supporté à partir de 4)
    AcReims\StatsBundle\Service\StatsInterface:
        alias: AcReims\StatsBundle\Service\Stats
    # Nom de service simplifé pour les appels depuis controleur
    ac_reims_stats.entity:
        alias: AcReims\StatsBundle\Service\Stats

