services:

    ### Service chargé de gérer le la collecte des attributs RSA
    AcReims\AuthRsaBundle\Service\AttributsRsa:
        public: true
        arguments: ['%ac_reims_auth_rsa.actif%', '%ac_reims_auth_rsa.attributs%', '@logger', '@request_stack']
    # Son alias nécessaire pour l'injection de dépendances dans un écouteur (sinon dépréciation à partir de symfony 3.3 et non supporté à partir de 4)
    AcReims\AuthRsaBundle\Service\AttributsRsaInterface:
        alias: AcReims\AuthRsaBundle\Service\AttributsRsa
    # Nom de service simplifé pour les appels depuis controleur
    ac_reims_auth_rsa.attributs:
        alias: AcReims\AuthRsaBundle\Service\AttributsRsa
