<?php

namespace AppBundle\Repository;

/**
 * SpoolTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpoolTacheRepository extends \Doctrine\ORM\EntityRepository
{
}
