<?php

namespace AppBundle\Repository;

/**
 * SpoolTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpoolTacheRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Supprimer les taches portant ce nom
	 *
	 * @param $nomTache 
	 */
	public function deleteTaches($nomTache)
	{
		// Création requête
		$delete = $this->createQueryBuilder("a")->delete();
		// clause where
		$delete->where('a.nomTache  = :nomTache')->setParameter("nomTache", $nomTache);

		// Retourne la requête
		return $delete->getQuery()->execute();
	}
}
