# La config de préprod est identique à celle de prod avec les compléments à partir de la ligne 5
imports:
    - { resource: config_prod.yml }

# On redirige les courrier vers une ou plusieurs adresses ou désactivation : pas de mail envoyé aux vrais destinataires
swiftmailer:
    disable_delivery: '%dev_preprod_disable_delivery_mail%'
    delivery_addresses: '%dev_preprod_list_delivery_mail%'

