imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
       # 15 jours de logs en local sur fichiers  
       main:
            type:           rotating_file
            max_files:      15
            path:           '%kernel.logs_dir%/%kernel.environment%.log'
            level:          debug

       # ET/OU utilisation de syslog
       # syslog:
       #     type:           syslogudp
       #     host:           '%syslog.host%'
       #     port:           '%syslog.port%'
       #     level:          debug
 
       # En cas d'erreur critique enregistre dans un fichier de log ET envoi un mail d'erreur
       main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
       grouped_critical:
            type:           group
            members:        [streamed_critical, buffered_critical]
       streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           '%kernel.logs_dir%/%kernel.environment%.critical.log'
            level:          debug
       buffered_critical:
            type:           buffer
            handler:        swift_critical
       swift_critical:
            type:           swift_mailer
            from_email:     '%critique_from%'
            to_email:       '%critique_to%'
            subject:        '%critique_subject%'
            level:          debug
       console:
            type: console
            process_psr_3_messages: false
