# Bundle interne de recette
app_recette:
    resource: '@RecetteBundle/Controller/'
    type: annotation

# Simultation de connexion RSA
ac_reims_simul_rsa:
    resource: '@AcReimsSimulRsaBundle/Controller/'
    type: annotation

_main:
    resource: routing.yml
