app:
    resource: '@AppBundle/Controller/'
    type: annotation

# Statistiques
ac_reims_stats:
    resource: '@AcReimsStatsBundle/Controller/'
    type: annotation

# Authentification
ac_reims_auth_rsa:
    resource: '@AcReimsAuthRsaBundle/Controller/'
    type: annotation


