app:
    resource: '@AppBundle/Controller/'
    type: annotation

# Statistiques
ac_reims_stats:
    resource: '@AcReimsStatsBundle/Controller/'
    type: annotation

# Authentification
ac_reims_auth_rsa:
    resource: '@AcReimsAuthRsaBundle/Controller/'
    type: annotation

# Charte graphique (bannière de maintenance entre autres)
ac_reims_charte_graphique:
    resource: '@AcReimsCharteGraphiqueBundle/Controller/'
    type: annotation

